### ISSUE TITLE
Update doesn't save file

### ISSUE THREAD

**Issue by wintery** [carrierwaveuploader/carrierwave-sequel#2]
I have a model with an image and I'm trying to call `update` on the model. The image will never save because `save_changes` returns `nil`.

Here's an example:

```ruby
class User < Sequel::Model
  mount_uploader :avatar, AvatarUploader

  set_allowed_columns :avatar
end

params[:user] = { avatar: File.open('image.jpg') }
user = User.first
user.update params[:user]
```

In this example, update returns `TypeError (can't convert nil into String)` because the `@avatar` instance variable on `user` is `nil` when `save_changes` is called, but if you call the `avatar` method on `user` it returns an object.

The workaround for now is to use `save` instead of update, or call update with another field that changes, but I'd like to not be forced to resave the entire object when it's not necessary.

**Comment by kuraga** [comment]
Any updates?

**Comment by kuraga** [comment]
> It seems the `@values` instance variable hash in `Sequel::Model` doesn't get updated

...cause [setter](https://github.com/carrierwaveuploader/carrierwave/blob/v0.10.0/lib/carrierwave/mount.rb#L162-L164) doesn't call [`super`](https://github.com/jeremyevans/sequel/blob/4.23.0/lib/sequel/model/base.rb#L858).

**Comment by kuraga** [comment]
Added a note in #8

**Comment by elado** [comment]
Thank god for that note @kuraga -- been trying to figure out the issue for an hour.

**Comment by mrbrdo** [comment]
submitted above PR with fix for this bug
